<a href="https://colab.research.google.com/github/sakarayajitesh/Q-Learning/blob/master/FrozenLake_v0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import gym
import random

In [2]:
env = gym.make("FrozenLake-v0")

/usr/local/lib/python3.6/dist-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


In [3]:
env.render()


SFFF
FHFH
FFFH
HFFG


In [5]:
state_size = env.observation_space.n
print(state_size)

16


In [6]:
action_size = env.action_space.n
print(action_size)

4


In [29]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
qtable.shape

(16, 4)

In [0]:
total_episodes = 15000
total_test_episodes = 100
max_steps = 99

learning_rate = 0.8
gamma = 0.95

epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.005

In [0]:
for episode in range(total_episodes):
  
  state = env.reset()
  step = 0
  done = False
  
  for step in range(max_steps):
    
    exp_exp_tradeoff = random.uniform(0,1)
    
    if exp_exp_tradeoff > epsilon:
      action = np.argmax(qtable[state,:])
      
    else:
      action = env.action_space.sample()
      
    
    new_state, reward, done, info = env.step(action)
    
    qtable[state,action] = qtable[state,action] + learning_rate * (reward + gamma * np.max(qtable[new_state,:]) - qtable[state,action])
    
    state = new_state
    
    if done == True:
      break
      
  episode += 1
  
  epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode) 
  

In [33]:
env.reset()
rewards = []

for episode in range(5):
  
  state = env.reset()
  step = 0
  done = False
  total_rewards = 0
  print("**************************************")
  print("EPISODE ",episode)
  
  for step in range(max_steps):
    
    env.render()
    
    action = np.argmax(qtable[state,:])
    
    new_state, reward, done, info = env.step(action)
    
    total_rewards += reward
    
    if done:
      rewards.append(total_rewards)
      print("Score", total_rewards)
      break
    
    state = new_state
    
env.close()
print("Score over time: " + str(sum(rewards)/total_test_episodes))
    

**************************************
EPISODE  0

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Down)
SFFF
FHFH
FFFH
HFFG
  (Right)
SFFF
FHFH
FFFH
HFFG
Score 1.0
*************************